name: Build and Release

on:
  push:
    branches: [ "test" ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact_name: modav
          - os: windows-latest
            artifact_name: modav.exe
          - os: macos-latest
            artifact_name: modav

    steps:
    - uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Build
      run: cargo build --release

    - name: Rename binary (Unix)
      if: matrix.os != 'windows-latest'
      run: mv target/release/modav target/release/${{ matrix.artifact_name }}

    - name: Rename binary (Windows)
      if: matrix.os == 'windows-latest'
      run: mv target/release/modav.exe target/release/${{ matrix.artifact_name }}

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.artifact_name }}
        path: target/release/${{ matrix.artifact_name }}

  create_release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Download artifacts
      uses: actions/download-artifact@v3

    - name: Upload Release Assets
      run: |
        for file in */*; do
          asset_name=$(basename "$file")
          asset_path="$file"
          echo "Uploading $asset_name..."
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Content-Type: $(file -b --mime-type $asset_path)" \
               --data-binary @"$asset_path" \
               "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ steps.create_release.outputs.id }}/assets?name=$asset_name"
        done
